# active spring boot profile
spring:
   profiles:
      active: development



---
# common spring boot configuration
spring:
   mvc:
      # Path pattern used for static resources
      static-path-pattern: /assets/**

      # Whether a "NoHandlerFoundException" should be thrown if no Handler was found to process a request
      throw-exception-if-no-handler-found: true
   web:
      resources:
         # Locations of static resources
         static-locations: classpath:/assets/

   thymeleaf:
      prefix : classpath:templates/
      check-template-location: true
      mode: HTML5
      suffix : .html
      cache : false

   # datasource
   datasource:
      driver-class-name: org.h2.Driver
      url: jdbc:h2:mem:test;DB_CLOSE_DELAY=-1;MODE=MYSQL
      username: sa
      password:

# mybatis
mybatis:
   config-location: classpath:mybatis/configuration.xml

# logging
logging:
   level:
      root: INFO 
         

---
# development profile: spring boot configuration
spring:
   config:
      activate:
         on-profile: development

   # devtools - live reload
   devtools:
      livereload:
         enabled: true

# server
server:
   port: 8080
   servlet:
      context-path: /
      encoding:
         charset: UTF-8
         enabled: true
         
---

# production profile: spring boot configuration
spring:
   config:
      activate:
         on-profile: production

# server
server:
   port: 8088
   servlet:
      context-path: /
      encoding:
         charset: UTF-8
         enabled: true